Repository dev-4-team/eye-on-frontend, pull requests merged in 2025-04, with the labels that each got.

#42 [FE] refactor : protest list sidebar closed when user clicked empty space
  src/app/(with-hamburger-button)/layout.tsx
  src/components/Protest/protest-list.tsx
Labels: refactor, frontend

#48 [FE] feat : add images for protest cheer
  public/images/check.gif
  public/images/marker.png
  public/images/torch.png
  src/app/verified/page.tsx
  src/components/KakaoMaps/KakaoMap.tsx
  src/components/Protest/ProtestMapMarker.tsx
  src/components/Protest/ProtestShareButton.tsx
  src/components/Verification/Verification.tsx
Labels: design, frontend

#49 [FE] feat : add socket effect
  package.json
  pnpm-lock.yaml
  src/app/protest/[id]/page.tsx
  src/components/Protest/ProtestCheeringButton.tsx
  src/components/Protest/ProtestDetailCheer.tsx
  src/hooks/useConfetti.tsx
  tsconfig.json
Labels: design, frontend

#47 [FE] : refactor total service for maintenance
  src/components/Button/CurrentLocationButton.tsx
  src/components/Button/CurrentLocationRestButton.tsx
  src/components/KakaoMaps/KakaoMap.tsx
  src/components/NaverDirections/NavigationRouteLines.tsx
  src/components/Protest/ProtestMapMarker.tsx
  src/components/Protest/ProtestMapMarkerList.tsx
  src/components/Verification/Verification.tsx
  src/hooks/useGeoLocation.tsx
  src/lib/utils.ts
Labels: refactor, frontend

#51 [FE] refactor : intergrate marker
  src/app/protest/[id]/page.tsx
  src/components/Button/index.tsx
  src/components/Protest/ProtestCheerBadge.tsx
  src/components/Protest/ProtestCheeringButton.tsx
  src/components/Protest/ProtestDetailCheer.tsx
  src/components/Protest/ProtestMapMarker.tsx
  src/components/Protest/ProtestMapMarkerList.tsx
  src/components/Protest/ProtestShareButton.tsx
  src/components/Verification/Verification.tsx
  src/components/ui/button.tsx
  src/hooks/useCheerEffect.ts
  src/hooks/useConfetti.tsx
  src/hooks/useSocketConnection.ts
  src/lib/utils.ts
Labels: refactor, design, frontend

#52 style : modify style
  src/components/Protest/ProtestMapMarker.tsx
  src/lib/socket.ts
Labels: design, frontend

#55 refactor: remove WebSocket implementation and switch to polling ans fix incorrect marker position
  src/app/layout.tsx
  src/app/providers/SocketProvider.tsx
  src/app/providers/TanStackProvider.tsx
  src/components/KakaoMaps/KakaoMap.tsx
  src/components/Protest/ProtestCheerBadge.tsx
  src/components/Protest/ProtestDetailCheer.tsx
  src/components/Protest/ProtestMapMarker.tsx
  src/hooks/UseProtestCheerCount.ts
  src/hooks/useCheerEffect.ts
  src/hooks/useSocketConnection.ts
  src/lib/ISoket.ts
  src/lib/socket.ts
  src/store/useProtestCheerStore.ts
  src/store/useSocketStore.ts
Labels: enhancement, refactor, frontend

#61 [FE] refactor : Optimize API Polling for Modal View State
  src/hooks/UseProtestCheerCount.ts
Labels: refactor, frontend

#65 [FE] Docs : update project README.md
  README.md
Labels: documentation, frontend

#69 [FE] remove : 불필요한 파일을 삭제한다
  my_key
  my_key.b64
  my_key.pub
Labels: frontend

#81 [FE] Bug : 드래그 시 시위 경로가 올바른 위치에서 벗어나는 문제를 해결한다
  src/components/KakaoMaps/KakaoMap.tsx
Labels: bug, frontend

#84 [FE] fix : 아이폰 16pro에서 상세페이지 접속시 화면에 스크롤이 생기는 문제를 해결하고 공유하기 버튼 디자인을 수정한
  src/app/protest/[id]/page.tsx
  src/components/Protest/ProtestShareButton.tsx
Labels: enhancement, design, frontend

#88 [FE] bug : 캐시 무효화가 작동하지 않는 버그를 해결한다
  next-sitemap.config.js
  src/apis/protest/index.ts
  src/app/(with-hamburger-button)/page.tsx
  src/app/v1/revalidate/protests/route.ts
  src/components/Protest/protest-list.tsx
Labels: bug, frontend

#89 [FE] Bug : heatmap의 리렌더가 과도하게 발생하여 canvas가 완전하지 않을 때 접근하여 발생하는 에러를 해결하고 리렌더를 최적화 한다
  src/components/KakaoMaps/KakaoMap.tsx
  src/hooks/useThrottledHeatmapUpdate.ts
  src/lib/utils.ts
Labels: bug, enhancement, frontend

#90 [FE] refactor : 디렉토리 구조 및 컨벤션 리팩토링 및 작업에대한 문서를 공유한다
  README.md
  src/api/cheer.ts
  src/api/protest.ts
  src/api/verification.ts
  src/apis/verification/index.ts
  src/app/(with-hamburger-button)/layout.tsx
  src/app/(with-hamburger-button)/page.tsx
  src/app/layout.tsx
  src/app/not-found.tsx
  src/app/oauth2/callback/page.tsx
  src/app/protest/[id]/page.tsx
  src/app/providers/TanStackProvider.tsx
  src/app/v1/revalidate/protests/route.ts
  src/components/Button/CurrentLocationButton.tsx
  src/components/Button/CurrentLocationRestButton.tsx
  src/components/Button/ProtestActionButton.tsx
  src/components/Footer/index.tsx
  src/components/GoogleAnalytics/GoogleAnalytics.tsx
  src/components/Header/index.tsx
  src/components/KakaoLogin/KakaoLogin.tsx
  src/components/KakaoMaps/KakaoMap.tsx
  src/components/KakaoMaps/MapErrorFallback.tsx
  src/components/KakaoMaps/MapLoadingFallback.tsx
  src/components/KakaoMaps/StaticKakaoMap.tsx
  src/components/Login/Login.tsx
  src/components/Modal/ModalWrapper.tsx
  src/components/NaverDirections/NavigationRouteLines.tsx
  src/components/Protest/MarkdownWrapper.tsx
  src/components/Protest/ProtestCard.tsx
  src/components/Protest/ProtestCheerBadge.tsx
  src/components/Protest/ProtestDetailCheer.tsx
  src/components/Protest/ProtestDetailInfo.tsx
  src/components/Protest/ProtestList.tsx
  src/components/Protest/ProtestMapMarker.tsx
  src/components/Protest/ProtestMapMarkerList.tsx
  src/components/Protest/ProtestShareButton.tsx
  src/components/Protest/VerificationBadge.tsx
  src/components/Verification/Verification.tsx
  src/constants/emojis.ts
  src/constants/protest.ts
  src/hooks/UseProtestCheerCount.ts
  src/hooks/useCheerEffect.ts
  src/hooks/useConfetti.tsx
  src/hooks/useMediaQuery.ts
  src/hooks/useSendCheerMutation.ts
  src/hooks/useThrottledHeatmapUpdate.ts
  src/lib/API/VerifyLocation.tsx
  src/lib/heatmap.ts
  src/lib/map.ts
  src/lib/utils.ts
  src/store/useUserInfoStore.ts
  src/types/kakaoMap.ts
  src/types/naverRoute.ts
  src/types/protest.ts
Labels: documentation, enhancement, refactor, frontend

#93 [FE] refactor : 위치 검증을 통한 인증 로직을 분리한다
  src/app/(with-hamburger-button)/page.tsx
  src/components/Verification/Verification.tsx
  src/hooks/useGeoLocation.tsx
  src/hooks/useLocationVerification.ts
  src/types/location.ts
Labels: refactor, Type

#95 [FE] refactor: 느슨했던 타입에 긴장감을 조성하려다 호되게 당하는 PR이 되었습니다.
  src/api/cheer.ts
  src/api/protest.ts
  src/api/verification.ts
  src/app/(with-hamburger-button)/page.tsx
  src/app/protest/[id]/page.tsx
  src/components/KakaoMaps/KakaoMap.tsx
  src/components/Protest/ProtestCard.tsx
  src/components/Protest/ProtestCheerBadge.tsx
  src/components/Protest/ProtestDetailCheer.tsx
  src/components/Protest/ProtestList.tsx
  src/components/Protest/ProtestMapMarker.tsx
  src/components/Protest/ProtestMapMarkerList.tsx
  src/hooks/useCheerEffect.ts
  src/hooks/useProtestCheerCount.ts
  src/hooks/useThrottledHeatmapUpdate.ts
  src/types/api.ts
  src/types/protest.ts
Labels: refactor, Type

#91 [FE] feature : 인증 완료 후 인증완료 페이지와 이동 로직을 추가한다
  src/app/verified/page.tsx
  src/components/Verification/Verification.tsx
  src/components/ui/button.tsx
Labels: enhancement, Type

#106 [FE] Bug : 리팩토링 과정에서 누락 된 경로 검증 로직을 추가하고 수정한다
  src/app/verified/page.tsx
  src/components/Verification/Verification.tsx
  src/hooks/useLocationVerification.ts
Labels: bug

#97 [FE] feat : 카카오 맵에 마커 클러스터러를 적용한다
  src/components/KakaoMaps/KakaoMap.tsx
  src/components/KakaoMaps/KakaoMapClusterer.tsx
  src/constants/clusterConfig.ts
Labels: feature, enhancement

#109 [FE] bug : geolocation error 처리 로직 수정 및 인증하기 실패시 버튼 디자인을 수정한다
  src/api/verification.ts
  src/components/Verification/Verification.tsx
  src/hooks/useLocationVerification.ts
Labels: bug, refactor, style

#103 [FE] refactor : 시위 응원하기 api를 훅에서 분리한다
  src/api/cheer.ts
  src/api/protest.ts
  src/hooks/useHeatMap.ts
  src/hooks/useSendCheerMutation.ts
  src/types/heatMap.ts
Labels: refactor

#115 [FE] refactor : 타입스크립트 설정을 강화하고 반영한다
  .eslintrc.json
  package.json
  pnpm-lock.yaml
  src/api/cheer.ts
  src/api/protest.ts
  src/api/verification.ts
  src/app/(with-hamburger-button)/layout.tsx
  src/app/(with-hamburger-button)/page.tsx
  src/app/layout.tsx
  src/app/protest/[id]/page.tsx
  src/app/providers/TanStackProvider.tsx
  src/components/Button/ProtestActionButton.tsx
  src/components/KakaoMaps/KakaoMap.tsx
  src/components/KakaoMaps/KakaoMapClusterer.tsx
  src/components/Modal/ModalWrapper.tsx
  src/components/NaverDirections/NavigationRouteLines.tsx
  src/components/Protest/ProtestCard.tsx
  src/components/Protest/ProtestDetailCheer.tsx
  src/components/Protest/ProtestList.tsx
  src/components/Protest/ProtestMapMarker.tsx
  src/components/Protest/ProtestMapMarkerList.tsx
  src/components/ui/sheet.tsx
  src/hooks/useGeoLocation.tsx
  src/hooks/useHeatMap.ts
  src/hooks/useLocationVerification.ts
  src/hooks/useNavigationRoutes.ts
  src/hooks/useThrottledHeatmapUpdate.ts
  tailwind.config.ts
  tsconfig.json
Labels: documentation, enhancement, refactor, Type

#120 [FE] refactor : 스크립트 중복 로드 문제를 해결하고 분석한다
  src/api/protest.ts
  src/app/layout.tsx
Labels: refactor

#119 [FE] refactor : 특정 시위 상세 모달에서만 스크롤이 생기는 문제를 해결한다
  src/app/protest/[id]/page.tsx
  src/components/Modal/ModalWrapper.tsx
  src/components/Protest/MarkdownWrapper.tsx
  src/components/Protest/ProtestDetailInfo.tsx
Labels: refactor, style

#118 [FE] Bug : 히트맵에서 11레벨 이상으로 줌 아웃 시 간헐적으로 발생하는 에러를 해결한다
  src/hooks/useThrottledHeatmapUpdate.ts
Labels: bug

#122 bug/#114 : 재검증 로직에 페이지 캐시 초기화를 추가한다
  src/api/protest.ts
  src/app/(with-hamburger-button)/page.tsx
  src/app/v1/revalidate/protests/route.ts
Labels: bug

#124 Bug/heatmap #123
  src/hooks/useThrottledHeatmapUpdate.ts
  src/lib/heatmap.ts
Labels: bug

#125 [FE] chore : 불필요한 조건을 제거하고 불필요한 주석 또한 제거한다
  src/hooks/useThrottledHeatmapUpdate.ts
Labels: style
