Repository dev-4-team/eye-on-frontend, pull requests merged in 2025-06, with the labels that each got.

#143 [FE] refactor : heatmap script sli hash를 env로 분리한다
  src/hooks/useHeatMap.ts
Labels: enhancement

#144 [FE] fix : 브라우저의 SRI 차단 문제를 해결한다
  src/hooks/useHeatMap.ts
Labels: bug

#145 [FE] chore : main 브랜치에 동기화를 진행한다
  src/hooks/useHeatMap.ts
Labels: enhancement

#146 [FE] Delete : github/workflows directory
  .github/workflows/deploy.yml
Labels: documentation

#147 [FE] docs : Readme.md 를 작성한다
  ProjectConvention.md
  README.md
Labels: documentation
