Repository dev-4-team/eye-on-frontend, pull requests merged in 2025-05, with the labels that each got.

#127 refactor/#126 : 백엔드 data 변경으로 인한 코드 수정 및 중복 호출하던 카카오 맵 문제를 해결하였습니다.
  src/app/favicon.ico
  src/app/layout.tsx
  src/types/protest.ts
Labels: bug, refactor, Type

#128 [FE] refactor : 타입 강화를 위한 프로젝트 컴포넌트 구조를 수정한다
  src/app/(with-hamburger-button)/page.tsx
  src/components/KakaoMaps/CurrentMapMarker.tsx
  src/components/KakaoMaps/KakaoMap.tsx
  src/components/KakaoMaps/MapControls.tsx
  src/components/NaverDirections/NavigationRouteLines.tsx
  src/components/Protest/ProtestMapMarkerList.tsx
  src/constants/map.ts
  src/hooks/useCurrentLocation.ts
  src/hooks/useKakaoLoader.tsx
  src/hooks/useMapState.ts
  src/types/kakaoMap.ts
Labels: refactor, Type

#130 [FE] feat : transformUtils 유틸 함수 테스트 코드 추가 및 예외 처리를 보완한다
  jest.config.ts
  jest.setup.ts
  package.json
  pnpm-lock.yaml
  src/app/protest/[id]/page.tsx
  src/components/Protest/ProtestMapMarker.tsx
  src/lib/transformUtils.test.ts
  src/lib/utils.ts
Labels: enhancement, test

#134 [FE] feat : 응원하기 실패시 로직을 강화한다.
  src/components/KakaoMaps/KakaoMap.tsx
  src/components/Protest/ProtestCheerBadge.tsx
  src/components/Protest/ProtestDetailCheer.tsx
  src/components/Protest/ProtestList.tsx
  src/components/Protest/ProtestMapMarker.tsx
  src/components/Protest/ProtestMapMarkerList.tsx
  src/hooks/useProtestCheerCount.ts
  src/hooks/useSendCheerMutation.ts
Labels: feature, enhancement, refactor

#135 [FE] bug : 하루가 지나면 데이터 갱신이 작동하지 않는 문제를 해결한다
  src/api/protest.ts
  src/api/verification.ts
  src/lib/utils.ts
Labels: bug

#137 [FE] bug : 리팩토링시 잘못 적용한 NavigationRouteLines 조건부 렌더링 로직을 수정한다
  src/components/NaverDirections/NavigationRouteLines.tsx
Labels: bug

#139 [FE] refactor : 히트맵 로직에서 불필요한 로직을 삭제한다
  src/hooks/useHeatMap.ts
Labels: refactor
