Repository dev-4-team/eye-on-frontend, pull requests merged in 2025-02, with the labels that each got.

#5 refactor : refactor protest detail UI for apply feedback
  src/app/(with-hamburger-button)/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/protest/[id]/page.tsx
  src/components/Footer/Footer.module.css
  src/components/Footer/index.tsx
  src/components/Header/Header.module.css
  src/components/Header/index.tsx
  src/components/Protest/protest-list.tsx
  src/lib/utils.ts
Labels: refactor, frontend

#10 Feature google analytics
  src/app/layout.tsx
  src/components/GoogleAnalytics/GoogleAnalytics.tsx
Labels: enhancement

#12 Feature seo
  next-sitemap.config.ts
  package.json
  pnpm-lock.yaml
Labels: enhancement

#14 [FE] refactor : UI improvements
  package.json
  pnpm-lock.yaml
  src/app/(with-hamburger-button)/page.tsx
  src/app/@modal/(.)protest/[id]/page.tsx
  src/app/protest/[id]/page.tsx
  src/components/Footer/Footer.module.css
  src/components/Header/Header.module.css
  src/components/KakaoLogin/KakaoLogin.tsx
  src/components/Protest/protest-card.tsx
  src/components/Protest/protest-list.tsx
  src/components/Protest/protest-md.tsx
  src/components/Verification/Verification.tsx
  src/components/ui/sheet.tsx
  src/lib/API/ProtestInfos.tsx
  src/lib/API/VerificationNumber.tsx
Labels: refactor, design, frontend

#17 [FE]] feat : Add protest URL share button and improve protest detail UI page
  src/app/protest/[id]/page.tsx
  src/components/Protest/ProtestShareButton.tsx
  src/components/Protest/protest-md.tsx
  src/components/Verification/Verification.tsx
Labels: refactor, frontend

#19 [FE] feat : 개인정보 이용 동의 문서 문구를 추가한다.
  src/app/protest/[id]/page.tsx
  src/components/Verification/Verification.tsx
  src/lib/API/ProtestInfos.tsx
  src/lib/API/VerificationNumber.tsx
Labels: design, frontend

#20 [FE] feat : add is mobile advice logic when verification excute
  src/components/Verification/Verification.tsx
  src/lib/utils.ts
Labels: enhancement, frontend

#22 feat: added keywords to meta tag
  src/app/(with-hamburger-button)/page.tsx
  src/app/protest/[id]/page.tsx
Labels: enhancement, frontend

#23 fix: added main keywords to title meta tag
  src/app/(with-hamburger-button)/page.tsx
  src/app/protest/[id]/page.tsx
Labels: enhancement, frontend

#24 refactor: fixed build error issue
  src/components/Verification/Verification.tsx
  src/lib/utils.ts
Labels: bug, frontend

#28 Feature seo keywords
  src/app/@modal/(.)protest/[id]/page.tsx
  src/components/Modal/ModalWrapper.tsx
Labels: bug, frontend

#29 refactor: fixed parellel routing issue
  src/components/KakaoLogin/KakaoLogin.tsx
  src/components/Login/Login.tsx
Labels: bug, frontend
