Repository dev-4-team/eye-on-frontend, pull requests merged in 2025-03, with the labels that each got.

#26 [FE] style : fix static kakaomap height calculate header footer
  .github/workflows/deploy.yml
  src/app/(with-hamburger-button)/page.tsx
  src/app/protest/[id]/page.tsx
  src/components/Footer/Footer.module.css
  src/components/Footer/index.tsx
  src/components/Header/Header.module.css
  src/lib/API/ProtestInfos.tsx
Labels: design, frontend

#34 Feature protest route
  src/app/(with-hamburger-button)/page.tsx
  src/app/api/directions/route/route.ts
  src/components/KakaoMaps/KakaoMap.tsx
  src/components/ui/button.tsx
Labels: enhancement, frontend

#36 fix: fixed /api prefix to /next-api
  src/app/next-api/directions/route/route.ts
  src/components/KakaoMaps/KakaoMap.tsx
Labels: bug, frontend

#31 인증수에 따른 z-index 조정 및 축적 기반 히트맵 반경을 조정한다
  .github/workflows/deploy.yml
  src/app/(with-hamburger-button)/page.tsx
  src/app/protest/[id]/page.tsx
  src/components/KakaoMaps/KakaoMap.tsx
  src/components/Protest/ProtestVerificationBadge.tsx
  src/components/Protest/VerificationBadge.tsx
  src/components/Protest/protest-list.tsx
  src/components/Protest/verification-badge.tsx
  src/components/Verification/Verification.tsx
  src/lib/API/ProtestInfos.tsx
  src/lib/API/VerificationNumber.tsx
  src/lib/utils.ts
Labels: refactor, frontend

#38 [FE] feat : add socket for protest cheer
  .prettierignore
  package.json
  pnpm-lock.yaml
  src/app/layout.tsx
  src/app/protest/[id]/page.tsx
  src/components/Header/index.tsx
  src/components/KakaoMaps/KakaoMap.tsx
  src/components/Protest/ProtestCheeringButton.tsx
  src/hooks/WebSocketContext.tsx
  src/hooks/useSendCheer.ts
  src/lib/socket.ts
  tsconfig.json
Labels: frontend
